---
dashboard:  
  image: vkovalyshyn/php-fs-dashboard
  environment:
   - PGSQL_USER=switch
   - PGSQL_PASS=switch
  privileged: true
  volumes:
    - www/app/controllers:/data/www/app/controllers:rw
    - www/app/models:/data/www/app/models:rw
    - www/app/views:/data/www/app/views:rw

db:
  image: postgres:9.4
  environment:
   - POSTGRES_USER=switch
   - POSTGRES_PASSWORD=switch
  volumes:
   - empty_dump_restore.sh:/empty_dump_restore.sh
  volumes_from:
   - dashboard
  ports:
   - "5432:5432"

php:  
  image: dylanlindgren/docker-laravel-phpfpm
  volumes_from:
    - dashboard
  links:
    - db:PGSQL_HOST
  privileged: true

web:  
  image: dylanlindgren/docker-laravel-nginx
  volumes_from:
    - dashboard
  links:
    - php:fpm
  ports:
    - "80:80"
  privileged: true
