---
dashboard:  
  image: vkovalyshyn/php-fs-dashboard
  privileged: true
  volumes:
   - ./mp3:/data/www/public/mp3

db:
  image: postgres:9.4
  environment:
   - POSTGRES_USER=switch
   - POSTGRES_PASSWORD=switch
  volumes:
   - ./db:/var/lib/postgresql/data
  volumes_from:
   - dashboard

php:  
  image: dylanlindgren/docker-laravel-phpfpm
  volumes_from:
    - dashboard
  links:
    - db:PGSQL_HOST
  privileged: true

web:  
  image: dylanlindgren/docker-laravel-nginx
  volumes_from:
    - dashboard
  links:
    - php:fpm
  ports:
    - "80:80"
  privileged: true

switch:
  image: webitel/freeswitch-base:vanilla
  privileged: true
  net: "host"
  volumes:
    - ./fs/logs:/logs
    - ./fs/conf:/etc/freeswitch
    - ./fs/scripts:/scripts
  volumes_from:
    -  dashboard
